### ISSUE TITLE
Malformed EVSE-ID

### ISSUE THREAD

**Issue by wurzelsepplde** [functionpointer/home-assistant-chargecloud-integration#2]
Hi, I have been searching for this integration for long, so happy I found it! Unfortunately I cannot add my local charger, always getting „ Malformed EVSE-ID“ error, e.g. for „DESWME052601“. I already tried adding * as separators, didn‘t help. Thanks a lot for your support!

**Comment by functionpointer** [comment]
Looks like you didn't add the separators in the correct places. The correct formatting for that particular one turns out to be `DE*SWM*E052601`.

I have pushed a new version that is more lenient. It just asks the API whatever you give it and will grab what comes back.
Try updating via HACS. It should accept your formatting and auto-correct it.

**Comment by wurzelsepplde** [comment]
Thanks a lot! Still getting an error, also with that format. I‘ll wait for your update.

**Comment by wurzelsepplde** [comment]
just updated it on HACS, and now it works! Thank you so much!

**Comment by functionpointer** [comment]
Did you verify this IRL or with comparison to a website?
I do see some states don't match with the state on https://ladenetz.de/lademap/, which is weird.

**Comment by wurzelsepplde** [comment]
Hey, it‘s really weird, I compared it to both, a different app and real life. Been ooh two days and now the status match….

**Comment by mountainbikert** [comment]
I'm trying to add a couple of chargers but I either get Cannot connect or Malformed ID.
For instance can you check on this location with https://ladenetz.de/lademap/

NL2704 - Shell Krogterijen
Backer en Ruebweg 2
4825 AA Breda

This is a Shell station with multiple chargers but I cannot add any of them. Same goes for all the Vattenfall chargers over here.

**Comment by functionpointer** [comment]
Thanks @mountainbikert.

I have released v0.2.1, which should fix the Shell station.
Unfortunately the API returns empty responses for the Vattenfall chargers.

The API calls expect a mysterious [OperatorID](https://github.com/functionpointer/pychargecloud/blob/master/src/chargecloudapi/api.py). Using the wrong one returns an empty response. I have managed to find three OperatorIDs in various places, and the integration tries them all. Maybe if we find another OperatorID the API would return data about the Vattenfall chargers.
The ladenetz.de website shows the status after all, so they do have the data.

**Comment by mountainbikert** [comment]
@functionpointer Thanks for your help! I'll try and find others that may work. Vattenfall has a large chunk of the market here so it would be awesome if you can get them to work. I checked the EVSE-ID and it's NLNUOEALF*0005738*1 but others contain more asteriks. So wouldn't it be something like NL*NUOE*ALF*0005738*1 because Vattenfall used to be NUON Energy and Alfen is the producer of the charger itself.

**Comment by mountainbikert** [comment]
@functionpointer Did you have a chance to look into the Nuon/vattenfall issue? It seems that all chargers starting with NLNUOEALF*0 have the same problem. Ladenetz.de is showing the correct status after all.
